- scripts/upmix.py
> script to convert stereo recordings to wave field

- scripts/upmix.py
- speaker_experiments/identity_sliding_fft.cc
simplifications to sliding fft + some script fixes (less treble as my wave field speaker has a bump over 10 kHz)
> sliding fft improvements

- speaker_experiments/identity_sliding_fft.cc
reduced rotators to 128 -- this seems to be able to produce reasonable frequency separation while maintaining decent quality
> more sliding fft refinements

- scripts/upmix.py
- speaker_experiments/revolve.cc
127,127,127,127,127,127,127,127,122,122,122,122,122,122,122,122 addresses partially a level difference between umc1820 and ultragain ada8200 -- in the past I have observed this level difference in other direction so it may have something to do with initialization or configurations of the devices
> more stable upmixing

- scripts/upmix.py
- speaker_experiments/revolve.cc
127,127,127,127,127,127,127,127,122,122,122,122,122,122,122,122 addresses partially a level difference between umc1820 and ultragain ada8200 -- in the past I have observed this level difference in other direction so it may have something to do with initialization or configurations of the devices
> lifting the phase information into spatialization

- speaker_experiments/identity_sliding_fft.cc
number of output channels is set to number of input channels
> identity_sliding_fft: support any number of input channels

- speaker_experiments/identity_sliding_fft.cc
This class handles both crating vector of rotators and multi-threading.
> identity_sliding_fft: add RotatorFilterBank class

- speaker_experiments/identity_sliding_fft.cc
This makes the aggregate filter's frequency response flatter.
> identity_sliding_fft: Change scaling of individual rotators.

- driver_model/driver_model.cc
- scripts/upmix.py
- speaker_experiments/revolve.cc
remove mono under 80 Hz and high pass 20 Hz
> simplified driver_model

- driver_model/driver_model.cc
- scripts/upmix.py
> simplification in the driver model

- driver_model/driver_model.cc
one more step in attempting to unify driver_model and revolve
> using the streaming data model in driver model

- scripts/upmix.py
- speaker_experiments/revolve.cc
> single .cc file solution

- speaker_experiments/identity_sliding_fft.cc
> transpose identity rotators

- speaker_experiments/identity_sliding_fft.cc
> convert complex numbers to floats

- speaker_experiments/identity_sliding_fft.cc
while this is 1 thread vs 40 before, it runs 30x faster than the 40 threaded version
likely memory access patterns are better or there are other explaning factors
> single threaded

- speaker_experiments/identity_sliding_fft.cc
separating rot and accu
accu will be the only per channel state
once completed this roughly halfs the memory use in multichannel use, asymptotically
> preparing to separate global and per channel state

- speaker_experiments/identity_sliding_fft.cc
runs a few percent faster when input and output are floats
> floatify -- convert I/O from double to float

- scripts/upmix.py
- speaker_experiments/revolve.cc
off-by-one bug fix for driver model -- looks like it wasn't active before this fix
> adding a simple binaural model

- scripts/upmix.py
- speaker_experiments/revolve.cc
some spatialization here already and for the one test sample I'm using this sounds more interesting and relaxing than the original
> improved binaural experience

- speaker_experiments/identity_sliding_fft.cc
- speaker_experiments/spectrum_similarity.cc
some bug fixes that more or less make this work again
phase coherence between filter buckets is an issue and there are many possibilities for improving it
> identity: changing from 10th order to 8th order

- speaker_experiments/revolve.cc
> rbetter quality of sound
